### PR TITLE
Keystone upgrade

### PR DESCRIPTION
**Pull request by aaronpowell**

### CODE REVIEW

**Comment by aaronpowell** [comment]
There's a bit more work to do, I'm still working out what is a legit error and what isn't in the logs

**Comment by borisno2** [comment]
> There's a bit more work to do, I'm still working out what is a legit error and what isn't in the logs

No worries, thanks for doing this @aaronpowell, shout out when you are done or if you need a hand...

**Comment by borisno2** [comment]
@aaronpowell Just having a look at a couple of things, a few of the `package.json` have `"next": "^11.0.0"` but the new keystone update uses `"next": "^11.1.0"` this might mess up a few things, and I suspect this will need to be updated too...

**Comment by aaronpowell** [comment]
@borisno2 finally got the build to pass!

**Comment by aaronpowell** [comment]
Just need to do a migration on the backend app, but I keep having it hang for me, no idea what's going wrong but it just sits at the "generate migration" step

**Comment by borisno2** [comment]
Need to run only the backend via `yarn dev:backend` to generate the migration... also fixed up an issue in the `next-config` template...

Looks good, thanks @aaronpowell!

**Comment by aaronpowell** [comment]
Oh, didn't think to run the backend standalone 🤦‍♂️

**Pull request merged**
